[package]
name        = "extmem"
version     = "0.0.1"
edition     = "2021"
description = "Rust code test for Cortex-M/cmake/C++ project"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com"]
license     = "MIT"

[dependencies]
# https://github.com/cbiffle/minimal-embedded-rust/blob/master/Cargo.toml

# [dependencies.cortex-m]
# version = "0.7.6"
# features = ["rt"]

# [dependencies.cortex-m-rt]
# version = "0.7.2"

# [dependencies.cortex-m-semihosting]
# version = "0.7.0"

# [dependencies.embedded-hal]
# version = "0.2.7"
# features = ["unproven"]

# [dependencies.heapless]
# version = "0.7.8"

# [dependencies.cortex-m-rtfm]
# version = "0.6.1"

# [dependencies.cortex-m-rtfm-macros]
# version = "0.6.1"

# [dependencies.cortex-m-log]
# version = "0.9.0"

# [dependencies.rtt-target]
# version = "0.4.0"

# [dependencies.rtt-logger]
# version = "0.2.1"

# [dependencies.panic-rtt-target]
# version = "0.1.6"

# [dependencies.embedded-hal-mock]
# version = "0.8.0"

# [dependencies.embedded-hal-mock-derive]
# version = "0.8.0"

# [build-dependencies]
# cortex-m-proc-macros = "0.9.1"
