[package]
name        = "extmem"
version     = "0.0.1"
edition     = "2021"
description = "Rust code test for Cortex-M/cmake/C++ project"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com"]
license     = "MIT"

[dependencies]
# https://github.com/cbiffle/minimal-embedded-rust/blob/master/Cargo.toml

# rtt-target = "0.6.1"
# panic-rtt-target = "0.2.0"
# rtt-logger = "0.2.1"
# cortex-m = "0.7.7"
# cortex-m-rt = "0.7.5"
# cortex-m-semihosting = "0.5.0"
# heapless = "0.8.0"
# cortex-m-rtfm = "0.5.3"

# [dependencies.embedded-hal]
# version = "0.2.7"
# features = ["unproven"]


# [dependencies.cortex-m-rtfm-macros]
# version = "0.6.1"

# [dependencies.cortex-m-log]
# version = "0.9.0"

# [dependencies.embedded-hal-mock]
# version = "0.8.0"

# [dependencies.embedded-hal-mock-derive]
# version = "0.8.0"

# [build-dependencies]
# cortex-m-proc-macros = "0.9.1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
# lto = true

# [profile.test]
# panic = "abort"

# [profile.bench]
# panic = "abort"

# [features]
# default = ["rtt"]
# rtt = ["rtt-target", "rtt-logger", "panic-rtt-target"]
